# Generated by Django 4.2.4 on 2023-08-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0003_alter_job_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
