# Generated by Django 4.2.4 on 2023-08-16 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0004_alter_job_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="content",
        ),
        migrations.AddField(
            model_name="job",
            name="company_details",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="date",
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="place",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="responsibilities",
            field=models.TextField(null=True),
        ),
    ]
