# Generated by Django 4.2.4 on 2023-08-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="score",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
