# Generated by Django 4.2.4 on 2023-08-11 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_candidate_domain"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Candidate",
        ),
    ]
